name: simple-api-workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "!**.md"
      - "!**.sql"
      - "!.gitignore"
      - "!MyPractice/**"
      - "SimpleAPI/**"
  pull_request:
    branches:
      - main
      - develop
jobs:
  simple-api-job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Step1
        run: echo "Run step2 in job1"
  simple-api-job2:
    needs: simple-api-job1
    runs-on: ubuntu-latest
    steps:
      - name: Step1 in job2
        run: echo "Run step1 in job2"
      - name: Step2 in job2
        run: echo "Run step2 in job2"
  simple-api-job3:
    needs: simple-api-job2
    runs-on: ubuntu-latest
    steps:
      - name: Step1 in job3
        run: echo "Run step1 in job3"
      - name: Step2 in job3
        run: echo "Run step2 in job3"
